### ISSUE TITLE
settings in root directory contains a particular ip address

### ISSUE THREAD

**Issue by Ds886** [Zackmon/FragmentServer_netCore#12]
Perhaps leftover of testing but it make it that you enable to run the program if it is not the machine ip
```
./runRelease.sh
1:51:00 PM:Server started on 192.168.86.167:49000

1:51:00 PM: Log Size = 100000

1:51:00 PM: Ping Delay = 5000ms

1:51:00 PM: Proxy Mode = False

Unhandled exception. System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at FragmentServerWV.Server.MainThread(Object obj) in /home/dash/dev/FragmentServer_netCore/FragmentServerWV_Core/Server.cs:line 74
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
./runRelease.sh: line 3: 2987321 Aborted                 (core dumped) ./FragmentServerWV_Console/bin/Release/netcoreapp3.1/FragmentServerWV_Console
```

Changing the IP to 0.0.0.0 resolve the issue

diff
```
diff --git a/settings.txt b/settings.txt
index c525097..6ebc743 100644
--- a/settings.txt
+++ b/settings.txt
@@ -1,9 +1,9 @@
 #edit to your local ip
-ip = 192.168.86.167
+ip = 0.0.0.0
 port = 49000
 
 #"is alive"-ping delay in ms
 ping = 5000
 
 #maximum log text length
-logsize = 100000
\ No newline at end of file
+logsize = 100000
```

**Comment by Zackmon** [comment]
yes the configuration is there from testing, but when we run the server for use to the public we configure it to 0.0.0.0

the default value should be 0.0.0.0
